#!/usr/bin/env bash
#
# parqet.beer fork setup
# ----------------------
# Bootstraps a fresh fork of parqet.beer for your own Cloudflare account:
#   - creates two KV namespaces (preview + production)
#   - generates a SESSION_SECRET_DEV for local development
#   - prints next-step instructions for editing wrangler.jsonc
#
# Safe to re-run: existing `.dev.vars` is never overwritten.

set -euo pipefail

BANNER='
============================================
  parqet.beer fork setup
============================================
'
printf '%s\n' "$BANNER"

# ---- prerequisite checks ------------------------------------------------
require() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    printf 'ERROR: required command "%s" is not installed.\n' "$cmd" >&2
    return 1
  fi
}

missing=0
require wrangler || missing=1
require openssl || missing=1
# jq is optional — we only use it for nicer parsing of wrangler output.
if ! command -v jq >/dev/null 2>&1; then
  printf 'NOTE: jq is not installed. KV namespace IDs will be parsed with sed instead.\n'
fi

if [ "$missing" -ne 0 ]; then
  printf '\nInstall the missing tools and re-run. Wrangler: `pnpm add -g wrangler`.\n' >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# ---- KV namespaces ------------------------------------------------------
#
# `create_kv` must return ONLY the namespace ID on stdout so callers can
# capture it with `$(...)`. Everything else (progress banners, raw wrangler
# output, errors) goes to stderr so the user still sees what's happening
# without corrupting the captured value. Earlier revisions printed the
# progress banner on stdout and the caller ended up with
# "Creating KV namespace: ... id = \"abcd\"" glued into wrangler.jsonc.
create_kv() {
  local title="$1"
  printf '\n--> Creating KV namespace: %s\n' "$title" >&2
  local out
  if ! out="$(wrangler kv namespace create "$title" 2>&1)"; then
    printf '%s\n' "$out" >&2
    printf 'ERROR: failed to create namespace "%s". Already exists? Check the Cloudflare dashboard.\n' "$title" >&2
    return 1
  fi
  # Mirror wrangler's raw output on stderr for visibility.
  printf '%s\n' "$out" >&2

  # wrangler prints something like:
  #   id = "abcd1234..."
  # or a JSON object when `--json` is used. Try JSON first for robustness.
  local id=""
  if command -v jq >/dev/null 2>&1; then
    id="$(printf '%s' "$out" | jq -r '.id // empty' 2>/dev/null || true)"
  fi
  if [ -z "$id" ]; then
    id="$(printf '%s' "$out" | sed -n 's/.*id[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)"
  fi
  if [ -z "$id" ]; then
    printf 'ERROR: could not extract KV id from wrangler output for "%s".\n' "$title" >&2
    return 1
  fi
  # ID on stdout — the ONLY thing the caller captures.
  printf '%s' "$id"
}

PREVIEW_ID="$(create_kv parqet-beer-preview || true)"
PROD_ID="$(create_kv parqet-beer-production || true)"

# ---- SESSION_SECRET_DEV -------------------------------------------------
DEV_VARS="$REPO_ROOT/.dev.vars"
if [ -f "$DEV_VARS" ]; then
  printf '\n--> .dev.vars already exists — leaving it untouched.\n'
else
  printf '\n--> Generating .dev.vars with a fresh SESSION_SECRET_DEV ...\n'
  SESSION_SECRET="$(openssl rand -base64 32)"
  cat >"$DEV_VARS" <<EOF
# Generated by scripts/setup-fork.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edit PARQET_CLIENT_ID below — see https://developer.parqet.com/
PARQET_CLIENT_ID=your-parqet-client-id-here
SESSION_SECRET_DEV=$SESSION_SECRET
EOF
  chmod 600 "$DEV_VARS"
  printf '    wrote %s (chmod 600)\n' "$DEV_VARS"
fi

# ---- next steps ---------------------------------------------------------
cat <<'NEXT'

============================================
  Next steps
============================================

1. Create a Parqet Connect OAuth app:
     https://developer.parqet.com/
   - Redirect URI (local):  http://localhost:5173/api/auth/callback
   - Redirect URI (prod):   https://YOUR-DOMAIN/api/auth/callback
   Copy the Client ID into `.dev.vars` (PARQET_CLIENT_ID) and into
   wrangler.jsonc under env.preview.vars.PARQET_CLIENT_ID and
   env.production.vars.PARQET_CLIENT_ID.

2. Edit wrangler.jsonc and replace these placeholders:
NEXT

if [ -n "${PREVIEW_ID:-}" ]; then
  printf '     env.preview.kv_namespaces[0].id    = "%s"\n' "$PREVIEW_ID"
else
  printf '     env.preview.kv_namespaces[0].id    = (run: wrangler kv namespace create parqet-beer-preview)\n'
fi
if [ -n "${PROD_ID:-}" ]; then
  printf '     env.production.kv_namespaces[0].id = "%s"\n' "$PROD_ID"
else
  printf '     env.production.kv_namespaces[0].id = (run: wrangler kv namespace create parqet-beer-production)\n'
fi

cat <<'NEXT'

3. Create the Secrets Store + session secret (production only):
     wrangler secrets-store store create parqet-beer --remote
     openssl rand -base64 32 | wrangler secrets-store secret \
       create <store-id> --name parqet_beer_session_secret \
       --scopes workers --remote
   Copy the store ID into env.production.secrets_store_secrets[0].store_id.

4. Set your custom domain in env.production.routes[0].pattern.

5. Add CF_API_TOKEN and CF_ACCOUNT_ID to your GitHub repo secrets so
   .github/workflows/deploy.yml can ship preview + production builds.

6. pnpm install && pnpm dev
============================================
NEXT
